openapi: "3.0.1"
info:
  version: 1.0.0
  title: Products API
  description: Products API Information

paths:
  /api/products:
    get:
      summary: List all products
      tags:
        - products
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
          required: false
          description: limit of products to get per page (optional)
        - in: query
          name: page
          schema:
            type: integer
          required: false
          description: page number (optional)
        - in: query
          name: sort
          schema:
            type: string
          required: false
          description: sort asc or desc (optional)
        - in: query
          name: query
          schema:
            type: string
          required: false
          description: filter by category (optional)
      responses:
        200:
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        500:
          description: Internal Server Error
    post:
      summary: Create a new product (required authentication as admin or premium user)
      tags:
        - products
      description:
        endpoint to create a new product in the database, required authentication as admin or premium user
      requestBody:
        description: Product object to be added
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        201:
          description: Product added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        400:
          description: Bad request
        401:
          description: Unauthorized
        500:
          description: Internal Server Error

  /api/products/{pid}:
    get:
      summary: Get 1 product by id
      tags:
        - products
      parameters:
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: Product id to get
      responses:
        200:
          description: Product by id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        404:
          description: Product not found
        500:
          description: Internal Server Error
    put:
      summary: Update 1 product by id (required authentication as admin)
      tags:
        - products
      description:
        endpoint to update a product in the database, required authentication as admin
      parameters:
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: Product id to update
      requestBody:
        description: Product object to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateProduct'
      responses:
        200:
          description: Product updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        400:
          description: Bad request
        401:
          description: Unauthorized
        404:
          description: Product not found
        500:
          description: Internal Server Error
    delete:
      summary: Delete 1 product by id (required authentication as admin)
      tags:
        - products
      description:
        endpoint to delete a product in the database, required authentication as admin
      parameters:
        - in: path
          name: pid
          schema:
            type: string
          required: true
          description: Product id to delete
      responses:
        200:
          description: Product deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        401:
          description: Unauthorized
        404:
          description: Product not found
        500:
          description: Internal Server Error
          
components:
  schemas:
    Product:
      type: object
      required:
        - title
        - description
        - code
        - price
        - stock
        - category
      properties:
        _id:
          type: string
          description: mongo ID autogenerated
        title:
          type: string
          description: Product title
        description:
          type: string
          description: Product description
        code:
          type: string
          description: Product code, must be unique
        price:
          type: number
          description: Product price
        stock:
          type: integer
          description: Product stock
        category:
          type: string
          description: Product category
        thumbnails:
          type: array
          items:
            type: string
            description: thumbnail url
          description: Product thumbnails
        status:
          type: boolean
          description: Product status
        owner:
          type: string
          description: Product owner
      example:
        _id: ObjectId(60b0a1a9b2e9a3b4b8a6b0a1)
        title: Intel Core i9 13900K
        description: Intel Core i9 13900K 3.5GHz 16-Core LGA 1700 Processor
        code: AA3
        price: 500000
        stock: 10
        category: Processors
        thumbnails:
          - https://cdn3.iconfinder.com/data/icons/education-209/64/bus-vehicle-transport-school-128.png
          - https://cdn3.iconfinder.com/data/icons/education-209/64/bus-vehicle-transport-school-128.png
        status: true
        owner: owner@owner.com
  requestBodies:
    updateProduct:
      type: object
      properties:
        title:
          type: string
          description: Product title
        description:
          type: string
          description: Product description
        code:
          type: string
          description: Product code, must be unique
        price:
          type: number
          description: Product price
        stock:
          type: integer
          description: Product stock
        category:
          type: string
          description: Product category
        thumbnails:
          type: array
          items:
            type: string
            description: thumbnail url
          description: Product thumbnails
        status:
          type: boolean
          description: Product status
      example:
        title: Intel Core i9 13900K
        description: Intel Core i9 13900K 3.5GHz 16-Core LGA 1700 Processor
        code: AA3
        price: 500000
        stock: 10
        category: Processors
        thumbnails:
          - https://cdn3.iconfinder.com/data/icons/education-209/64/bus-vehicle-transport-school-128.png
        status: true
        
